/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.locadoracarro.frontend;
import com.imrob.locadoracarro.App;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   
}
